version: "3.8"

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules  # Solo este volumen, opcional
    command: npm run dev